name: j02-actions
run-name: ${{ github.actor }} hulu brothers
on: [push]
jobs:
  runs-j02-with-zulu-17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      # 安装 xvfb
      - name: Install xvfb
        run: sudo apt-get install -y xvfb
      
      - name: Compile Java files
        run: |
          javac -cp "lib/*" -d . asciiPanel/*.java
          javac -cp "lib/*" -d . hulu/*.java
          javac -cp "lib/*" -d . *.java
      
      # 使用 xvfb-run 运行程序
      - name: Run application with xvfb
        run: |
          xvfb-run -a java Main &
          sleep 5  # 等待5秒让程序启动
          kill $!  # 结束程序